### PR TITLE
Added Bubble Nano support

### PR DESCRIPTION
**Pull request by bubbledevteam**
1.Added Bubble Nano support
2.Update Bubble/Bubble Mini/Bubble Nano appId

### CODE REVIEW

**Comment by paulplant** [comment]
Thanks for the PR. 🙏

Please can you confirm which Libre sensors/markets can be used with the new Nano and also confirm if you the team has successfully tested them as working?

**Comment by paulplant** [comment]
> Thanks for the PR. 🙏
> 
> Please can you confirm which Libre sensors/markets can be used with the new Nano and also confirm if you the team has successfully tested them as working?

@bubbledevteam , please can you feedback on this? It's important for us to be able to correctly document this change. Thanks!

**Comment by bubbledevteam** [comment]
> > Thanks for the PR. 🙏
> > Please can you confirm which Libre sensors/markets can be used with the new Nano and also confirm if you the team has successfully tested them as working?
> 
> @bubbledevteam , please can you feedback on this? It's important for us to be able to correctly document this change. Thanks!

Hi ,typically Nano support to read all Libre sensor types except Libre 3.
But as you know ,it needs to decode the sensor (Libre 2 US/Libre 2+), this part cannot be done by Nano.

So let me explain in detail the devices supported by Nano:
All sensors that support Gen2 encryption are currently unable to work with Nano + xdrip because Gen2 provides encryption protection for connections and data. This encryption needs to be handled at the app level. If xdrip can handle Gen2 key generation and raw data decryption, then Nano can support it; Nano has a separate command for this purpose.

It is rumored that there is a derivative version of xdrip in the community that can work with Nano to support Gen2 series sensors, but its algorithm library is not open source.

Gen 2 sensor types include: 2B, 2C, which covers Libre 2 US/AUS/CA/NZ/RU and Libre 2+ LA.

As it stands, the sensors that Nano and the current xdrip code can support include:
1–Libre 1, DF, A2 Type
2–Libre 1 US, E5, E6 Type
3–Libre 2/2+ EU, 9D, C5, C6 Type
4–Libre Pro/H: 70 Type

**Comment by paulplant** [comment]
OK thanks... I didn't really mean the implementation of the decoding in the app, just the end-result for the users with the current PR.

So this means that the Nano behaves exactly the same as the previous Bubble transmitters, right? There is no functional difference to the Nano. So therefore there is no change needed to the documentation except to add the Nano name. 

Correct?

> As it stands, the sensors that Nano and the current xdrip code can support include: 1–Libre 1, DF, A2 Type 2–Libre 1 US, E5, E6 Type 3–Libre 2/2+ EU, 9D, C5, C6 Type 4–Libre Pro/H: 70 Type

Can you confirm if you have physically tested each of these sensors using xDrip4iOS and the new Nano? Or somebody in your Beta groups?

It's just to know. Thanks!

**Comment by bubbledevteam** [comment]
> OK thanks... I didn't really mean the implementation of the decoding in the app, just the end-result for the users with the current PR.
> 
> So this means that the Nano behaves exactly the same as the previous Bubble transmitters, right? There is no functional difference to the Nano. So therefore there is no change needed to the documentation except to add the Nano name.
> 
> Correct?
> 
> > As it stands, the sensors that Nano and the current xdrip code can support include: 1–Libre 1, DF, A2 Type 2–Libre 1 US, E5, E6 Type 3–Libre 2/2+ EU, 9D, C5, C6 Type 4–Libre Pro/H: 70 Type
> 
> Can you confirm if you have physically tested each of these sensors using xDrip4iOS and the new Nano? Or somebody in your Beta groups?
> 
> It's just to know. Thanks!

I just checked the wiki:

Bubble and Bubble Mini transmitters are not currently compatible with xDrip4iOS if using the newer "C5" Libre 2 EU sensors
--For this part ,Nano now supports it .

We have conducted extensive physical testing on all of the above sensor types. Since the communication protocol remains consistent, there is essentially no difference for xdripswift. This PR is more focused on code cleanliness and compatibility.

Additionally, we have tested some Gen2 Type sensors. By using an online decryption algorithm that returns 344 bytes in the same format as Libre 1, we were able to call xdripswift’s transmitter algorithm, and it works just the same.

**Pull request merged**
