### PR TITLE
LibreLibreUp follower mode

### LINKED ISSUE #440: Libre 3 support
Is Libre 3 already support, or any outlook on when support can be expected? 

I did see some workarounds using Jugglio or something for the standard xDrip app. Curious how close we are with this Swift package.

Thanks!

### PR DESCRIPTION
**Pull request by paulplant**
Will connect and pull the patient's CGM values using their LibreLinkUp account as a new data source follower option.

- allow upload to Nightscout server if entered/enabled in the settings
- automatic detection and redirection based upon the server response
- will display the user account country (doesn't do anything useful, it's just interesting)
- will work the same as the current NightscoutFollowManager and use a silent audio to try to maintain the app running in the background to download periodic updates, upload to Nightscout and trigger alarms etc as required.
- new data source section added, with enumerated follower sources (to easily add new options in the future without re-writing the UI again)
- NightscoutFollowerDelegate renamed to FollowerDelegate and used as a common delegate for both Nightscout and LibreLinkUp follower modes
- NightscoutBgReading renamed to FollowerBgReading and a new initializer added to accept LibreLinkUpFollowManager readings.
- settings screen will dynamically update when login is successful and active sensor is pulled from the servers
- automatically stopping further login attempts if there is an authentication error, to avoid account lockout. This will be reset once the user updates their e-mail/password.
- UI will inform the user that they need to accept the latest conditions of use (maybe this could be automated in the future?)
- attempt to auto-detect and display sensor type based upon the (incomplete) serial number sent by LLU response. If it fails, it just shows the (incomplete) serial number. Once we get user feedback regarding newer sensor types, this can be updated to cover more regions/markets/sensors.
- LibreLinkUp version is changeable from within Developer Settings incase they update their app. The user can just edit this value here instead of waiting for us to update xDrip4iOS. (We should update the version in the ConstantsLibreLinkUp.swift file so that all new installs use it)

image

Will close #440

### CODE REVIEW

**Comment by crsohr** [comment]
Cool feature, though: is it something we want in the core of `xdripswift`?

Not sure their API is public, and not sure we have a “legal” binding to request data from LLU. 

At the very least maybe we could add the hostname as a configurable option (without providing a default value) but still we might still infringe on their rights.

What are your thoughts about this?

**Comment by paulplant** [comment]
We considered this before working on it...

The reason we've been holding off for so long is to see the reaction to other apps using this method. So far, there has been no reaction at all.

We are not writing any data at all to the servers - this was something we've always respected to avoid problems.

I thought about obfuscating the API URLs, but they are already published in many different places and projects in the public realm without any issues.

**Comment by gui-dos** [comment]
I had to change the watchOS Deployment target from 7.0 to 10.0 otherwise also the main xdrip target doesn’t compile for me with the latest betas:

Screenshot 2023-10-25 at 20 10 45

**Comment by paulplant** [comment]
Also https://github.com/JohanDegraeve/xdripswift/pull/473/commits/60874af5fdedcf350c89120940fbe76776062b75 would close #460

**Comment by paulplant** [comment]
Background keep-alive can now be set to normal (as always), aggressive, or completely disabled.

When disabled, the app will not fire any alarms, updates, notifications or anything whilst in the background meaning battery usage will be almost zero.

Aggressive is the same as normal, but the "silent sound" is played every 2 seconds instead of every 5.

The user is fully informed (including changes to operation and battery impact) about this when changing these options.

Simulator Screenshot - iPhone 15 - 2023-11-13 at 13 18 28

Simulator Screenshot - iPhone 15 - 2023-11-13 at 13 18 44

**Pull request merged**
