### PR TITLE
Support Libre2

### PR DESCRIPTION
**Pull request by bubbledevteam**
Support Libre2

### CODE REVIEW

**Comment by paulplant** [comment]
Hi @bubbledevteam , is there any way to re-use these commits to enable access to Libre 2 from MiaoMiao or Droplet transmitters?

**Comment by bubbledevteam** [comment]
> Hi @bubbledevteam , is there any way to re-use these commits to enable access to Libre 2 from MiaoMiao or Droplet transmitters?

Hello, the decryption algorithm runs on the server, so if you feed it with right data in right format ,it doesn't matter with which device you use.

Here is a very clear reference about how MM can work with it:
https://github.com/gui-dos/xdripswift/commit/f510a84?fbclid=IwAR2eZLZy-vOlVMn-of181eHpcFXLnxv06GW1qt3mA1Fu4ZURdv6SpCom5eM

But pls remember that I don't the MM firmware and protocol and I don't check the code above.

In Bubble side, Bubble Team just wants to contribute to the lovely community

**Comment by gui-dos** [comment]
You can easily get the patchInfo also from a BluCon:

https://github.com/gui-dos/DiaBLE/blob/e3952322f1896204cd570824cfe56d2775289768/DiaBLE/Devices/BluCon.swift#L164-L171

Notice that the suffix of the command to request the patchInfo corresponds to the custom NFC command “0xA107” (https://github.com/gui-dos/DiaBLE/blob/e3952322f1896204cd570824cfe56d2775289768/DiaBLE/Devices/BluCon.swift#L76)

(Unfortunately I can’t get the patchInfo of a Libre 2 via NFC like the last iOS build of DiaBox seems to be able to do).

Anyway, if you decompile the LinkBluCon apk you can discover that even Ambrosia is using the glucose.space server themselves… :)

**Comment by JohanDegraeve** [comment]
Hi,

thanks for the PR. I'm missing documentation in the PR. 
I wrote some guidelines which you must adhere to : https://github.com/JohanDegraeve/xdripswift/wiki/Pull-Requests

With the current status of the PR it will take more time for me to include the changes.

thanks,

Johan

**Comment by gui-dos** [comment]
I am wearing now a Libre sensor whose patchInfo starts with 0xA2.

@bubbledevteam: I see you have introduced a second endpoint, “callnox”, which doesn’t require the patchInfo, neither an accessToken, only a “userId” parameter.

Why are the 0xA2 sensors so special to require a further API?

I see you are using structs which are more similar to the ones used in @dabear’s miaomiao-client-swift: are you beginning to use his Swift code on the server side?

**Comment by dabear** [comment]
Please make sure to stop internal web server if you accept this pr. No one should be using loop with a real time dependency on an internet connection (that is actually considered hazardous)

**Comment by JohanDegraeve** [comment]
Libre 2 support will be available soon.

**Pull request closed without merging**
