### PR TITLE
russian translate

### PR DESCRIPTION
**Pull request by znv569**

### CODE REVIEW

**Comment by JohanDegraeve** [comment]
thanks for doing the translations

**Comment by znv569** [comment]
Good morning. I wanna ask you. Will there be support for the new sensor
libre 3?

**Comment by JohanDegraeve** [comment]
as far as I know, the to Libre 3 data is not yet decrypted. 
Some people have been trying but without success.
Personally I'm not busy with this because it's beyond my knowledge

**Comment by znv569** [comment]
[image: image.png]

It seems there is already success with some developers. There is also some
progress in this project.
As soon as it works. I'll try to transfer it to xdrip

https://github.com/gui-dos/DiaBLE

Thank you a lot for your answer! Have a nice day! )

пн, 22 авг. 2022 г. в 15:02, Johan Degraeve ***@***.***>:

**Comment by JohanDegraeve** [comment]
we're changing the wording for "treatments_insulin"
because some people are giving the amount of basal, but it should only be bolus
so we change the word to 
"treatments_insulin" = "Bolus"

Is it possible for you to give a new Russian translation?

**Comment by znv569** [comment]
ok! It's simple

"treatments_insulin" = "Болюс"
I can check app and fix all translation sometimes. I will make new MR
sometimes.

вс, 28 авг. 2022 г. в 23:09, Johan Degraeve ***@***.***>:

**Comment by znv569** [comment]
Here I also agree. Doesn't sound very good. Tomorrow I will send a new
short version.

пн, 5 сент. 2022 г. в 14:50, Paul Plant ***@***.***>:

**Comment by znv569** [comment]
Good day. I also corrected a couple of names.

пн, 5 сент. 2022 г. в 15:23, Никита Заремба ***@***.***>:

**Pull request merged**
