### PR TITLE
Finnish translations

### PR DESCRIPTION
**Pull request by makotila**

### CODE REVIEW

**Comment by JohanDegraeve** [comment]
merged in branch develop 

May I ask to make PR's on develop branch ? and also not to change/or reset the Signing related fields like Team and Bundle Identifier

**Comment by makotila** [comment]
Thank you! Yes, I do next time, sorry about that

**Comment by JohanDegraeve** [comment]
can you also a test with develop branch ?

**Comment by makotila** [comment]
I tried translations in develop in simulator (iPhone SE (2020) and iPhone 12 mini). Is there some way to test translations, for example Fastlane could be used to run tests and for example to take screenshots with different languages?

**Comment by JohanDegraeve** [comment]
I don't know. I test everything on device (iPhone SE 2020). The test the language I would need to change my phone to Finnish but I assume you have your phone in Finnish ?

**Pull request closed without merging**
