### PR TITLE
basic data export implementation

### PR DESCRIPTION
**Pull request by noah-fl**
please review and I'm open for comments

### CODE REVIEW

**Comment by KevinDenys** [comment]
Thank you for developing this

**Comment by JohanDegraeve** [comment]
I measured the time to execute this statement :
let readings = bgReadingsAccessor.getLatestBgReadings(limit: nil, howOld: nil, forSensor: nil, ignoreRawData: false, ignoreCalculatedValue: true)

it was 330 ms on an iPhone SE 2021

Then an iteration is done through all readings to do json serialization,
this took 600 ms

This is too long to run in the main thread. I don't know if you tested this on slower (older) devices. But if it takes too long, the app may crash. 
Because it runs on the main = UI thread. UI thread should not be used to execute long duration tasks.
You can see also it takes some time (at least on my device), before the sharing options are opened. I wonder what will happen if a bluetooth device is sending a new reading during the period that those readings are fetched
(note that all bluetooth communication runs on the main thread)
I recommend to use this function https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/Core%20Data/accessors/BgReadingsAccessor.swift#L148
with managed object context being a private managed object context.  Also the json serialization should happen on a background thread
There are sample usage of this, example in the chartmanager.

on this line https://github.com/JohanDegraeve/xdripswift/blob/d0355eb619ff7a9409b57c465e2334e390b0abcc/xdrip/View%20Controllers/Root%20View%20Controller/RootViewController.swift#L1523
what is being deleted here ?
all files ?

usage of print
https://github.com/JohanDegraeve/xdripswift/blob/d0355eb619ff7a9409b57c465e2334e390b0abcc/xdrip/View%20Controllers/Root%20View%20Controller/RootViewController.swift#L1529
Please use trace in stead. In case of issues, users may send a problem report, and it will include what you write there


better to move exportAllReadings to a seperate module and not in the rootviewcontroller.

I propose to make a seperate folder in Utilities, and there a new swift file that has this function
You could also add a type of export (here it's json), so we could later add other types like csv ..

In general
- when defining variables, functions, add comments everywhere
- also document all statements, even if it's obvious what the statement does
- use more spacing

I know it takes some time but for me you can not document too much

**Comment by noah-fl** [comment]
You're right. Maybe I will come up with a better implementation of this functionality.

**Comment by paulplant** [comment]
@noah-fl are you still working on this?

**Comment by noah-fl** [comment]
> @noah-fl are you still working on this?

Not really, I'm too busy these days.

**Pull request closed without merging**
