### PR TITLE
LibreTools

### PR DESCRIPTION
**Pull request by ivalkou**
This is the integration of my [LibreTools library](https://github.com/ivalkou/LibreTools).

It can read, restart and activate L1 sensors.

NFC functionality requires iOS 13.0, but I made it so that the library can be imported into the project with target version 10.0.
The corresponding section in the settings will simply not be displayed.

I could not include the sensor unlock code and password in the library for obvious reasons. Instead, a user can enter them himself. They are not a secret, and I can provide them at any time.

Simulator Screen Shot - iPhone SE (1st generation) - 2020-07-27 at 11 56 04
Simulator Screen Shot - iPhone SE (1st generation) - 2020-07-27 at 11 56 27
Simulator Screen Shot - iPhone SE (1st generation) - 2020-07-27 at 11 57 13

### CODE REVIEW

**Comment by gui-dos** [comment]
Without some sort of explanations and inline comments, I don’t think Johan is going to accept such pull request.

To my understandings, the two least intuitive points in your technique to reinitialize a sensor are:

* You are overwriting the mirrored patch table of the custom commands A0-A4/E0-E2 in FRAM (which correspond to the real higher memory at 0xFFAC) by redirecting the 0xA2 command (which locks again the memory blocks unlocked by 0xA4) to call the ROM implementation of the 0xE0 command (which reinitializes a sensor and is disabled by factory: https://github.com/captainbeeheart/openfreestyle/blob/master/api/freestylelibre_api.h).

* After overwriting the address of the 0xA2 command and the CRC checksum of its memory region, you are not calling it directly but you simply call the “getPachInfo” command (0xA1) which supposedly calls the 0xA2 command at the end by itself. Then you restore the original address and checksum and you call again the 0xA2 command to lock the memory blocks effectively.

Did I grasp it?

**Comment by ivalkou** [comment]
@gui-dos I redirect the A1 command to E0 command address. Then I call A1, the sensor is reset, then I restore the command table to its original state.

**Comment by ivalkou** [comment]
And about comments. You do not impose requirements on other dependencies that are imported to the project. They are written with their own code style. 

As far as the code I wrote in xdrip directly, it fits the requirements.

**Comment by gui-dos** [comment]
The commands are defined in a reverse order, you’re right, I didn’t grasp it the first time. Your implementation know looks streamlined even to a naive programmer like me :) Thanks for your explanation!

I wrote a very basic NFCReader class where I am using read/writeMultipleBlocks. I discovered that while you can read three blocks at a time you can write only two (https://github.com/gui-dos/DiaBLE/blob/master/DiaBLE/NFC.swift). I tried to allow reading/writing behind the block boundaries as @travisgoodspeed ’s [GoodV](https://github.com/travisgoodspeed/GoodV) is doing and it seems to work.

Adding a “Scan” button to the top right of xDrip4iOS is therefore easily feasible. If you try to scan a Libre 2 with DiaBox, you can see from the log that @bubbledevteam is using an old implementation of my class which I corrected in the meantime.

**Comment by JohanDegraeve** [comment]
I'll handle the PR soon

**Comment by hansdampf01** [comment]
Just to give my two cents on it. There is a high chance Abbott will ask Apple to take down XDrip4iOS when this gets implemented. Even from TestFlight. Marek did a long post after a call with Apple about his EDropletNFC that Apple told him they will take it down and ban it even from TestFlight if he tries to distribute it with that.

**Comment by ivalkou** [comment]
@hansdampf01  is right. This is why I have not included write access keys in my code. However, I want this feature to be available to everyone. If Johan decides not to accept my pull request, that's okay.

**Comment by gui-dos** [comment]
@ivalkou: I noticed that your Libre2.decryptFRAM() is symmetric and that you can encrypt decrypted data.

Have you tested the new Bubble 2.6 firmware?

@bubbledevteam has introduced the new glucose.space endpoint  “libreoop2AndCalibrate” for decrypted data (https://github.com/bubbledevteam/bubble-client-swift/commit/0284fd98) but it seems possible now to pass to the original libreoop2 manually encrypted data. Unfortunately I can’t test it because I own only expired Libre 2 sensors currently.

**Comment by JohanDegraeve** [comment]
- is there some manual for it and for the different options

- what is the reason for having an unlock code ?

- the unlocking is it done in the libretools itself ? means there's some hash of the secret stored in the libretools project ?
I'm actually not in favor of such an unlockcode.

- there's an option "Read FRAM", but probably that reading will not be processed by the libre data parser ?

**Comment by gui-dos** [comment]
According to the paper [Security analysis of a Connected Glucose Sensor for Diabetes](https://fortinetweb.s3.amazonaws.com/fortiguard/research/techreport.pdf) "command identifier, password and code details have been **censored from request of the vendor**."

Marek Macner is also reporting that  it was the same "Vendor" to request his eDroplet to be taken down from the Apple Store.

However you can find on GitHub many other detailed resources, like this visual map of the FRAM: https://github.com/captainbeeheart/openfreestyle/blob/master/docs/reverse.

For the first time I discovered the location of the maximum life of a sensor (~ 14.5 days) as calibrated in the factory, fram[326...327], which is specific to each sensor.

fram[322...323] seems to correspond to the sensor patchInfo[2...3]; I discovered that on Libre 2 the first byte is not null, therefore you have to get the region only from the second byte.

**Pull request closed without merging**
