### PR TITLE
small fix

### PR DESCRIPTION
**Pull request by znv569**

### CODE REVIEW

**Comment by paulplant** [comment]
The idea of this PR was to fix the errors with the Russian text strings introduced in the previous PR #372 .

The problem was that the translations for SpeakReadings.strings didn't make sense and users complained about the Voice function sounding awful and all speech was far too long.

But in this new PR, you have only slightly edited one of the strings. What happened?

image

**Comment by znv569** [comment]
I didn't change much.  Each one sounds better in its own way.  there is a
typo in this line.  An error in the word, which I corrected.  It's good
when someone can offer some other options.

I was also confused by some of the names that I fixed.  It's strange that
people have long offered a subscription to xdrip with a Russian translation
for money.  Why do it for money.  When it was possible to translate for
everyone.

**Comment by znv569** [comment]
can be shortened a bit.  today I will send another version and this mr.

**Comment by znv569** [comment]
I'm talking about this version, which is under iOS. Someone has already
translated, sells for a fee.

I misunderstood you at first. I thought that which is now the current
translation is already proposed by someone. Mine was before. I made it
shorter. Now I went to run and protested. By the way, the first option that
I suggested, it sounds exactly the same as in English. Your current glucose
is.

People got used to the previous version. I shortened.

вт, 6 сент. 2022 г. в 19:17, Paul Plant ***@***.***>:

**Comment by paulplant** [comment]
Do you have any information about this "paid version" of xDrip4iOS in Russian? Can you share with us privately by e-mail:  xdrip@proximus.be ?

**Comment by znv569** [comment]
Can you use Localizable.stringsdict?
because I noticed the mistake.

Symbol S at the end of word hour hours is wrong.

[image: IMG_4145.jpg]

вт, 6 сент. 2022 г. в 21:09, Paul Plant ***@***.***>:

**Comment by znv569** [comment]
I added more improve! Tested carefully.

**Pull request merged**
