### PR TITLE
Merge pull request #4 from JohanDegraeve/master

### PR DESCRIPTION
**Pull request by bubbledevteam**
Hello ，Johan

we want to add graph for the homescreen，do you have any idea about it？

there are lots of open source graph libs，for example :
https://github.com/danielgindi/Charts

IF you have any ideas ,let us know pls, we can integrate it very soon.

### CODE REVIEW

**Comment by JohanDegraeve** [comment]
Hi,

no I have no idea. 

Johan

**Comment by birdfly** [comment]
image

**Comment by bubbledevteam** [comment]
image

what we have done

**Comment by JohanDegraeve** [comment]
Looks good so far, improvement still ongoing ?
IMG-1734

**Comment by bubbledevteam** [comment]
fixed，try the newest

**Comment by JohanDegraeve** [comment]
graph has been implemented with SwiftCharts

**Pull request closed without merging**
