### PR TITLE
FastLane and GitHub Actions for Mac-free install, for semi-automated TestFlight distributions.

### PR DESCRIPTION
**Pull request by bjornoleh**
Based on FastLane and GitHub Actions from LoopKit/LoopWorkspace.

Known issue: the build number for the TestFlight distributions is reset to 1, and incremented by 1 for each build by Fastlane. No big deal perhaps. There might be solutions to this

Edit: the build number is not reset, it’s set to last TestFlight build number +1. If you have distributed before, it could be build Nr 4175+1. If you haven’t used TestFlight before, it could be build Nr 1 or 2. 

It is possible to set the GitHub actions to trigger periodically by cron, or have it trigger by releases on origin. This version only require manually syncing in GitHub, then start the GithUb Actions workflow manually.

The build takes around seven minutes, then some time for processing at TestFlight.

Instructions in /fastlane/Testflight.md

The LoopKit version was introduced here:
https://loop.zulipchat.com/#narrow/stream/144182-development/topic/FastLane.20.2B.20GitHub.20Actions.20.2B.20TestFlight.20.3D.20Mac-free.20Loop/near/315841670

And implemented in Loop with this PR:
https://github.com/LoopKit/LoopWorkspace/pull/26

### CODE REVIEW

**Comment by bjornoleh** [comment]
I ended up removing /Pods from .gitignore temporarily to be able to change the deployment target of Pods targets. Hence the long list of changed files. This may not have been the most elegant way, but it worked for my purpose. Please advise if this should be handled differently.

**Comment by bjornoleh** [comment]
I should mention that gemfile.lock is copied directly from LoopKit/LoopWorkspace, and could probably be pruned a bit to remove unused dependencies. Perhaps the build could be ever so slightly faster. But it doesn’t seem to break anything. 

https://github.com/JohanDegraeve/xdripswift/blob/50a7dbb9bbada210008f3209723d4008226cc855/Gemfile.lock

**Comment by paulplant** [comment]
@bjornoleh - we've now merged the transition to Swift Package Dependencies into develop. 

Would you mind making a new PR on the new develop branch so that it is all "clean"?

Basing your PR on the new develop will also make it much smaller and easier to manage

**Comment by bjornoleh** [comment]
Closing this in favour of https://github.com/JohanDegraeve/xdripswift/pull/419 to simplify the PR now that pods are removed from the project.

**Pull request closed without merging**
