### PR TITLE
App Name Parameterization

### PR DESCRIPTION
**Pull request by paulplant**
All text strings and localisations now use the ConstantsHomeView.applicationName constant. There is no longer any app name hardcoded into the project UI.

### CODE REVIEW

**Comment by paulplant** [comment]
#197

**Comment by JohanDegraeve** [comment]
Swedish was just added in development branch, there's also xDrip4iO5 appearing there, would still need to be replaced by %@

**Comment by paulplant** [comment]
Ok. I'll pull the new localization soon, fix it and commit into this PR

**Comment by paulplant** [comment]
Swedish translation changes done

**Pull request merged**
