### PR TITLE
German translation for Common.stings

### PR DESCRIPTION
**Pull request by Sn1kk3r5**
German translation

### CODE REVIEW

**Comment by Sn1kk3r5** [comment]
German translation

**Review by Sn1kk3r5 — COMMENTED** [review]
Did a review over my own translations

**Comment by JohanDegraeve** [comment]
Hi,
did you finish all translations ?
Johan

**Comment by Sn1kk3r5** [comment]
Hi Johan, 

Yes I did. 

Cheers
Cris

**Pull request merged**
