### PR TITLE
use configuration files

### PR DESCRIPTION
**Pull request by noah-fl**
Xcode build configuration files used to define several settings.

### CODE REVIEW

**Comment by JohanDegraeve** [comment]
merged in develop branch

removed the config files from the git repository, they can be downloaded

If I keep them there, everyone who wants to do a PR will include updated versions of that file

see also https://github.com/JohanDegraeve/xdripswift/wiki/xCode

thanks for the nice work !

**Comment by noah-fl** [comment]
I'd strongly recommend including xDrip.xcconfig and Version.xcconfig in the repo, they only should be changed at a new release. They contain only default values which are required. 

All modifications should be done in the optional files (xDripConfigOverride.xcconfig, VersionOverride.xcconfig) and they could be added to .gitignore after the initial commit to prevent PRs including them.

**Comment by noah-fl** [comment]
why was the Version.xconfig removed [here](https://github.com/JohanDegraeve/xdripswift/commit/55140637ae403947e1e4232d63c90cece8142735)?

**Comment by JohanDegraeve** [comment]
It's not useful to have the version info in a seperate config file
that can be included in the commits, useful for instance for Paul Plant who always follows my releases, so he knows when there's a new release

**Comment by noah-fl** [comment]
Well, the Verision.xconfig change should be part of a new release. Without that it requires 8 changes in xdrip.xcodeproj  for a new version, instead of 2 with the Version.xconfig.

**Comment by JohanDegraeve** [comment]
If I want to release a new version, then I update the version in xcode, 
and I push the updated file xdrip.xcodeproj/project.pbxproj
anyone who wants to build pulls the changes

**Comment by noah-fl** [comment]
Creating a new release doesn't need to be different. Just make the changes in the Version.xconfig, push the update, create a new tag and/or create a new release. Please correct me if I'm wrong. 

The main advantage using that Version.xconfig file is, that it minimises the required version changes to 2 instead of 8 and a new version would not require a manually merge of the project file if it was changed in a local dev environment.

**Comment by JohanDegraeve** [comment]
You're right, can you check the latest status develop branch? is it ok ?

**Comment by noah-fl** [comment]
Looks good, just did a quick check. A fresh checkout with an override file works and gives the actual version.

**Pull request closed without merging**
