### PR TITLE
5.3.0 Staging

### PR DESCRIPTION
**Pull request by paulplant**
- New iOS and WatchOS notifications including glucose charts and custom content extension (a new target is required for this)
- Snooze All feature now available to silence ALL alarms during set amount of time.
- Snooze status (nothing snoozed, some non-urgent alarms snoozed, some urgent alarms snoozed, or all alarms snoozed) is shown in the snooze view and also in the Home Screen snooze icon.
- New "Loop Share" workflow. Disabled by default, but can be set to the following:
   - Disabled (same as old "Suppress Loop Share" setting)
   - Loop/iAPS (shares only to the existing/usual LoopKit App Group)
      - group.com.${DEVELOPMENT_TEAM}.loopkit.LoopGroup
   - Trio (shares only to a new Trio App Group)
      - group.org.nightscout.${DEVELOPMENT_TEAM}.trio.trio-app-group
      - allows compatibility to https://github.com/nightscout/Trio/pull/314
      - until the above is merged into Trio master/main, the existing Loop/iAPS option will work for Trio users.
- "Loop Share" renamed to "OS-AID Share" to encompass all DIY systems
- autostart G6 sensor when detected
- Dexcom ONE+ compatibility added
- new dynamic view for .systemSmall widget to generate a simpler, high contrast view which looks good in StandBy mode at night with the red tint.
- new option in Developer for "StandBy Night Mode". This will enable the above view (only when the view is used in StandBy mode) automatically between 22hrs and 08hrs. Kept in Developer Settings for now - could be removed all together (and enabled always) in the future if no real need is found for it.
- fastlane build file updated to add new target (the new Trio app group must be added manually to the user's Apple Developer account before trying to build)

Simulator Screenshot - iPhone 15 Pro - 2024-06-30 at 14 51 59

IMG_7852

IMG_7857

### CODE REVIEW

**Comment by marionbarker** [comment]
I was not able to run GitHub Action Add Identifiers with version from this PR [log file](https://github.com/loopdocs-tester/xdripswift/actions/runs/9750466247)
* I updated the Gemfile.lock file to Fastlane 2.221.1 and tried again [log file](https://github.com/loopdocs-tester/xdripswift/actions/runs/9750566495)
* Then I read the fine print - there's a syntax error in Fastfile:

```
[!] Syntax error in your Fastfile on line 62: Fastfile:62: syntax error, unexpected string literal, expecting ']'
        "com.#{TEAMID}.xdripswift.xDri...
        ^
Fastfile:63: syntax error, unexpected ']', expecting `end'
      ]
      ^
Fastfile:211: syntax error, unexpected string literal, expecting ']'
        "com.#{TEAMID}.xdripswift.xDri...
        ^
Fastfile:212: syntax error, unexpected ']', expecting `end'
      ]
      ^
Fastfile:258: syntax error, unexpected `end', expecting end-of-input
```

I'll make that fix and report back.

**Comment by marionbarker** [comment]
With those updates, I can run GitHub Action: Add Identifiers.
I created a PR to Paul's branch.
I will now continue adding the Trio App Group to the identifiers, create certificates and see if I can build.

**Comment by marionbarker** [comment]
Because I built previously with Mac-Xcode, the xdrip identifier already had the Trio App Group in addition to the Loop App Group.

It was not clear to me if any of the other identifiers needed to have both app groups - I assume no because they didn't get it from the Mac-Xcode build. I added Trio App Group anyway because I don't think it hurts, but this should be clarified in testflight.md.

[GitHub Build Action was successful](https://github.com/loopdocs-tester/xdripswift/actions/runs/9750840074)

**Comment by marionbarker** [comment]
## Summary
Success
* May need additional feature request for case using a pump with no heartbeat

## Details
Install the TestFlight build onto a phone with matching Trio build that uses Trio App Group.
* Was using the mac-xcode build with this Trio before
   * xDrip4iOS getting CGM data from NS configured to Share with OS-AID and selected Trio 
   * Trio was operating with pump that has a heartbeat, working with phone locked
* Installed the TestFlight version, confirmed operation continued with phone locked as before
* Swapped to Simulator pump (no heartbeat)
   * Confirm green loop continues while phone is unlocked
   * Lock phone at 15:22, checked at 15:30, Live Activity showed Trio had stopped - last loop at 15:17, xDrip was active

## Question
Is there a setting that can be used to make xDrip4iOS act as a heartbeat in this situation where the pump does not have a heartbeat and there is no CGM on the phone?
* If no, this is not a blocker for this version, but a request for later to support Dana pumps
* If yes, let me know how to configure the app and I'll test that case

**Comment by paulplant** [comment]
> With those updates, I can run GitHub Action: Add Identifiers. I created a PR to Paul's branch. I will now continue adding the Trio App Group to the identifiers, create certificates and see if I can build.

Hi Marion. Sorry, I've been away on business for several days. I'll check and merge the PR shortly!

**Comment by paulplant** [comment]
> ## Question
> Is there a setting that can be used to make xDrip4iOS act as a heartbeat in this situation where the pump does not have a heartbeat and there is no CGM on the phone?
> 
> * If no, this is not a blocker for this version, but a request for later to support Dana pumps
> * If yes, let me know how to configure the app and I'll test that case

OK perfect. So we can give green light to the main item that we were trying to address which was the switchable sharing to a new Trio app group as needed.

The heartbeat request for make Trio work with the Dana pump is a different topic so we'll work on it separately, ok?

**Comment by dnzxy** [comment]
@JohanDegraeve there were outstanding changes PR‘d to @paulplant‘s staging branch that are now missing. Should that be PR‘d to xdripswift dev directly or still go through Paul‘s repo?

**Comment by alexanderkorchevskiy** [comment]
> * group.org.nightscout.${DEVELOPMENT_TEAM}.trio.trio-app-group

I can't build after the latest updates (I am on 5.2.3 and my last update was around June) and addition of Trio app group.
Here is the mistake description I get when trying to build:
"Provisioning profile "match AppStore com.***.xdripswift.xDripNotificationContextExtension" doesn't match the entitlements file's value for the com.apple.security.application-groups entitlement. Profile qualification is using entitlement definitions that may be out of date. Connect to network to update. (in target 'xDrip Notification Context Extension' from project 'xdrip')"

I added Trio group to xDripNotificationContextExtension identifier - that didn't help. Any ideas what shall I do on top of that? Thanks.

**Pull request merged**
