### PR TITLE
WebServices capacity

### PR DESCRIPTION
**Pull request by clvsjr9**
Trying to make a contribution to the xdripswift project by creating new functionality through WebServices to integrate with smartwatches and others apps like Loop, etc.

Using features and capabilities offered by the Telegraph library: https://cocoapods.org/pods/Telegraph

Main objective is to offer equivalent capacity to that available in the Spike app with more current features and allow better integration between varied applications.

// Define the Nightscout API v1 routes
// SiDiary WebServices generation capacity
// xdripswift Loop CGM Manager using plugin and communicating via WebServices messages
// Others capabilities that can be useful...

### CODE REVIEW

**Comment by JohanDegraeve** [comment]
Ok I'll have a look. This may take some time. I will try to understand the code and might add comments and maybe do changes. That depends.

Can you give a few hints how to test this ?

**Comment by clvsjr9** [comment]
Do not worry about time. It's not urgent and we can evolve as much as possible.

I created a class called WebServicesManager that aims to implement all WebServices capabilities using handlers (swift functions) that match the URLS.

Example: http://127.0.0.1:2020/entries/current should produce a JSON result in the future like:
[{"_id": "15784310250805a11dbe0545", "filtered": 145176, "dateString": "2020-01-07T21: 03: 45.000Z", "rssi": 100, "device": "MIAOMIAO", "type" : "sgv", "noise": 1, "date": 1578431025028, "direction": "FortyFiveUp", "sgv": 125, "unfiltered": 145176, "sysTime": "2020-01-07T21: 03: 45,000Z "," utcOffset ": 0}]

To test remove the comments on the start function of the class and analyze the reports in the log:

         // Demonstrate client requests and web socket connection
         // demoClientNormalRequest ()
         // demoClientJSONRequest ()
         // demoWebSocketConnect ()

You can additionally open a browser and enter your intranet URL and receive the result via GET. Example:

http://192.168.1.5:2020/status

**Comment by JohanDegraeve** [comment]
This is at the moment still draft ? I can't figure out what it's doing.
Why is ReachabilitySwift needed ? I understood the goal is to work offline ? so why need to know if the network is reachable ?

**Comment by clvsjr9** [comment]
I'd like to test the returns values (WebServices Requests) from my computer that connect to local intranet. Can be disabled when all offline work to be done...
The big objective is to offer the equivalent capability found in the Spike app 
I don't know how to get the corrects values from CoreData that returns Nightscout API v1 correctly.

**Comment by miki3421** [comment]
Hello, i'm very interested to this function because i want to try to avoid to use Spike. 
This version of Xdrip is amazing. Stable and very accurate. Can't wait to test with Loop. 
I'm available for testing in case of.

**Comment by JohanDegraeve** [comment]
someone found an easy way to integrate with loop : https://github.com/julian-groen/xdripswift/blob/master/xdrip/Managers/LoopManager/LoopManager.swift

(it's probably similar that was has been proposed here)

to integrate, a user would need to build Loop with groupname
group.com.loopkit.xdripclient

**Comment by miki3421** [comment]
Hi,
I've already integrated with loop, there are two different ways.
Just using Health Database ( is working also off line ) or to have also the
trend using Nightscout share server.

Michele


Il giorno gio 16 apr 2020 alle ore 08:46 Johan Degraeve <
notifications@github.com> ha scritto:

**Comment by clvsjr9** [comment]
Can I close this PR ?

**Comment by JohanDegraeve** [comment]
keep it open please, it reminds me that I need to do this.
I'll probably do the changes proposed by Julian Groen (which you also proposed ? don't remember exactly)

**Comment by JohanDegraeve** [comment]
can be closed now. The next release will offer an option for users to build the app themselves and integrate with Loop

**Pull request closed without merging**
