### PR TITLE
Added option to select language

### PR DESCRIPTION
**Pull request by Jon-b-m**
Added settings bundle for preferred language in xDrip settings (in iPhone settings).

### CODE REVIEW

**Comment by JohanDegraeve** [comment]
I wonder how this works.
I tried on one phone and indeed I can go to the iOS settings, search for 'xDrip4iO5' and it shows me these settings

Then tried on another phone, didn't immediately see the language setting, but then all of a sudden it was there

**Comment by Jon-b-m** [comment]
It should work on every iPhone. I'm no expert in this. I got the info from here: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/UserDefaults/Preferences/Preferences.html

The preferences language setting is always included in the template, even when you delete all other items this setting stays.

**Comment by JohanDegraeve** [comment]
Apparently changing app language is possible in iOS settings since iOS 13
It works also without this PR.

So I guess this can be closed ?

**Comment by Jon-b-m** [comment]
Oh, 😳😂

**Comment by JohanDegraeve** [comment]
:)
It's good to know that language can be changed so easily.
I always changed my phone language to do this, but it can be done much easier now

**Pull request closed without merging**
